trigger: none

# Defines carbon-apimgt branch
resources:
  repositories:
  - repository: MVNBuildforPipeline 
    type: github
    name: slahirucd7/MVNBuildforPipeline
    source: slahirucd7/MVNBuildforPipeline  
    endpoint: slahirucd7

# Defines Pipeline file stored in carbon-apimgt master branch
  pipelines:
  - pipeline: loggingPipeline
    source: slahirucd7.carbon-apimgt
    trigger: true

stages:
- stage: MainStage
  displayName: Checkout to carbon-apimgt repo
  jobs:
  - job: 'GettingPullRequestDetails'
    displayName: Getting PullRequest Details
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: DownloadBuildArtifacts@0
    #   displayName: 'Downloading variables'
    #   inputs:
    #     buildType: 'specific'
    #     project: 'FromPocToScenarioTesting'
    #     pipeline: 'slahirucd7.carbon-apimgt'
    #     buildVersionToDownload: 'latest'
    #     downloadType: 'specific'
    #     downloadPath: '$(System.ArtifactsDirectory)'
    
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'FromPocToScenarioTesting'
        pipeline: 'slahirucd7.carbon-apimgt'
        buildVersionToDownload: 'latest'
        targetPath: '$(System.ArtifactsDirectory)'
        
    - script: cat $(System.ArtifactsDirectory)/variables/pipeline.env
      displayName: 'Restore Enviornment Variables'
    - script: |
        echo "PRNumber:$(PRNumber)"
      displayName: 'echo PR number using env variables'

    - checkout: MVNBuildforPipeline
    
    - script: |
        ls
    

      

