trigger: none

resources:
  repositories:
  - repository: MVNBuildforPipeline 
    type: github
    name: slahirucd7/MVNBuildforPipeline
    source: slahirucd7/MVNBuildforPipeline  
    endpoint: GitConnection

    # trigger:
    #   branches:
    #    include:
    #      - master
    #      - testBranch
    #      - b3
    # pr:
    #   branches:
    #     include:
    #     - master 
    #     - testBranch
  
  ###########################   DO NOT DELETE    #############################
  # pipelines:
  # - pipeline: simpleEmptyPipeline
  #   source: ChoreoEmptyPipeline
  #   trigger: true
  ##########################    DO NOT DELETE    #############################
  
  pipelines:
  - pipeline: loggingPipeline
    source: slahirucd7.carbon-apimgt
    trigger: true


stages:
- stage: MainStage
  displayName: Checkout to repo
  jobs:
  - job: Listing_directory
    displayName: Listing Directory
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download variables'
      inputs:
        buildType: 'specific'
        project: 'Choreo'
        pipeline: 'slahirucd7.MVNBuildforPipeline'
        buildVersionToDownload: 'latest'
        downloadType: 'specific'
        downloadPath: '$(System.ArtifactsDirectory)'

    - script: cat $(System.ArtifactsDirectory)/variables/pipeline.env
      displayName: 'Restore Enviornment Variables'
    - script: |
        # echo "FOO:$(FOO)"
        echo "PRNumber:$(PRNumber)"
        # echo $PRNumber
      displayName: 'echo env variables'

      

